"""pictures belongs to users

Revision ID: 3ad88e584b9d
Revises: b96ae456e6d8
Create Date: 2026-04-08 13:30:26.122979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ad88e584b9d'
down_revision: Union[str, Sequence[str], None] = 'b96ae456e6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Déjà appliqué manuellement via des tentatives partielles précédentes — no-op
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pictures_idpictures', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'pictures', ['pictures_idpictures'], ['idpictures'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index(op.f('ix_users_pictures_idpictures'), 'users', ['pictures_idpictures'], unique=False)
    op.create_index(op.f('idx_users_pictures'), 'users', ['pictures_idpictures'], unique=False)
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_index(op.f('ix_pictures_users_idusers'), table_name='pictures')
    op.drop_column('pictures', 'users_idusers')
    # ### end Alembic commands ###
