"""sync species and users with MLD

Revision ID: c881aba2fc9d
Revises: 1c17a5539771
Create Date: 2026-04-08 12:18:01.943742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c881aba2fc9d'
down_revision: Union[str, Sequence[str], None] = '1c17a5539771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('species_url_picture', sa.String(length=100), nullable=True))
    op.drop_column('species', 'sex')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_verified')
    op.add_column('species', sa.Column('sex', mysql.VARCHAR(length=45), nullable=True))
    op.drop_column('species', 'species_url_picture')
    # ### end Alembic commands ###
